"""add books and book item type

Revision ID: 231a1a6686c6
Revises: 32502c3addcb
Create Date: 2026-09-15 15:17:42.265890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231a1a6686c6'
down_revision: Union[str, None] = '32502c3addcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic's autogenerate can't detect enum value additions, so this is
    # added by hand: the item_type enum backs reading_status/list_items/
    # notes/graph_edges polymorphically, and now needs a third value.
    op.execute("ALTER TYPE item_type ADD VALUE IF NOT EXISTS 'book'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('first_publish_year', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('open_library_id', sa.String(), nullable=True),
    sa.Column('open_library_url', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('open_library_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
    # Postgres has no ALTER TYPE ... DROP VALUE — removing 'book' from
    # item_type would require rebuilding the enum and every column using it.
    # Not worth it for a local dev downgrade; the unused value is harmless.
