"""initial schema

Revision ID: 32502c3addcb
Revises: 
Create Date: 2026-09-15 14:48:17.232923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32502c3addcb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('paper', 'article', name='item_type'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('paper', 'article', name='item_type'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.Enum('manual', 'citation', name='edge_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'target_type', 'target_id', 'edge_type', name='uq_edge')
    )
    op.create_table('lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('paper', 'article', name='item_type'), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('quote_text', sa.Text(), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('topic_tag', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('paper', 'article', name='item_type'), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('unread', 'read', 'skimmed', name='reading_state'), nullable=False),
    sa.Column('in_queue', sa.Boolean(), nullable=False),
    sa.Column('in_reference', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_type', 'item_id', name='uq_reading_status_item')
    )
    op.create_table('researchers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('orcid', sa.String(), nullable=True),
    sa.Column('openalex_id', sa.String(), nullable=True),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('faculty_page_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openalex_id'),
    sa.UniqueConstraint('orcid')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('academic_api', 'rss', name='source_kind'), nullable=False),
    sa.Column('track', sa.Enum('research', 'journalism', name='source_track'), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('is_user_added', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_query', sa.String(), nullable=False),
    sa.Column('translated_query', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('cadence', sa.Enum('realtime', 'daily', 'weekly', name='cadence'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('origin_source_id', sa.UUID(), nullable=True),
    sa.Column('is_from_user_source', sa.Boolean(), nullable=False),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['origin_source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('paper', 'article', name='item_type'), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'item_type', 'item_id', name='uq_list_item')
    )
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_source_id', sa.UUID(), nullable=True),
    sa.Column('is_from_user_source', sa.Boolean(), nullable=False),
    sa.Column('oa_status', sa.Boolean(), nullable=False),
    sa.Column('oa_url', sa.String(), nullable=True),
    sa.Column('landing_url', sa.String(), nullable=True),
    sa.Column('openalex_id', sa.String(), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['origin_source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openalex_id')
    )
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.create_table('seen_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id')
    )
    op.create_table('paper_authors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('author_order', sa.Integer(), nullable=False),
    sa.Column('is_corresponding', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'researcher_id', name='uq_paper_researcher')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_authors')
    op.drop_table('seen_log')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_table('papers')
    op.drop_table('list_items')
    op.drop_table('articles')
    op.drop_table('topics')
    op.drop_table('sources')
    op.drop_table('researchers')
    op.drop_table('reading_status')
    op.drop_table('notes')
    op.drop_table('lists')
    op.drop_table('graph_edges')
    # ### end Alembic commands ###
