"""make note item_type and item_id nullable for freeform notes

Revision ID: 77fae48a65ff
Revises: 231a1a6686c6
Create Date: 2026-09-15 15:37:28.172896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77fae48a65ff'
down_revision: Union[str, None] = '231a1a6686c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'item_type',
               existing_type=postgresql.ENUM('paper', 'article', 'book', name='item_type'),
               nullable=True)
    op.alter_column('notes', 'item_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'item_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('notes', 'item_type',
               existing_type=postgresql.ENUM('paper', 'article', 'book', name='item_type'),
               nullable=False)
    # ### end Alembic commands ###
