"""add full_text cache column to papers

Revision ID: a6593d4dfba5
Revises: 123fb6af24cd
Create Date: 2026-09-15 16:34:30.911816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6593d4dfba5'
down_revision: Union[str, None] = '123fb6af24cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('full_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'full_text')
    # ### end Alembic commands ###
